/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ServiceBooking = IDL.Record({
  'technicianName' : IDL.Text,
  'bookingDate' : Time,
  'notes' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlertSeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const AlertEntry = IDL.Record({
  'isAcknowledged' : IDL.Bool,
  'message' : IDL.Text,
  'severity' : AlertSeverity,
});
export const ShopOrder = IDL.Record({
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const HydrotechUserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'customWebId' : IDL.Text,
  'email' : IDL.Text,
});
export const ValveName = IDL.Text;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeAlert' : IDL.Func([IDL.Nat], [], []),
  'addPersistentServiceBooking' : IDL.Func([ServiceBooking], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearPersistentState' : IDL.Func([], [], []),
  'createPersistentAlert' : IDL.Func([AlertEntry], [IDL.Nat], []),
  'getAlerts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, AlertEntry))],
      ['query'],
    ),
  'getCallerServiceBookings' : IDL.Func(
      [],
      [IDL.Vec(ServiceBooking)],
      ['query'],
    ),
  'getCallerShopOrders' : IDL.Func([], [IDL.Vec(ShopOrder)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(HydrotechUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPersistentValveState' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(HydrotechUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'persistValveState' : IDL.Func(
      [IDL.Vec(IDL.Tuple(ValveName, IDL.Bool))],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([HydrotechUserProfile], [], []),
  'setPersistentValveState' : IDL.Func([IDL.Nat], [], []),
  'submitPersistentShopOrder' : IDL.Func([ShopOrder], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ServiceBooking = IDL.Record({
    'technicianName' : IDL.Text,
    'bookingDate' : Time,
    'notes' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlertSeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const AlertEntry = IDL.Record({
    'isAcknowledged' : IDL.Bool,
    'message' : IDL.Text,
    'severity' : AlertSeverity,
  });
  const ShopOrder = IDL.Record({
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const HydrotechUserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'customWebId' : IDL.Text,
    'email' : IDL.Text,
  });
  const ValveName = IDL.Text;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeAlert' : IDL.Func([IDL.Nat], [], []),
    'addPersistentServiceBooking' : IDL.Func([ServiceBooking], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearPersistentState' : IDL.Func([], [], []),
    'createPersistentAlert' : IDL.Func([AlertEntry], [IDL.Nat], []),
    'getAlerts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, AlertEntry))],
        ['query'],
      ),
    'getCallerServiceBookings' : IDL.Func(
        [],
        [IDL.Vec(ServiceBooking)],
        ['query'],
      ),
    'getCallerShopOrders' : IDL.Func([], [IDL.Vec(ShopOrder)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(HydrotechUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPersistentValveState' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(HydrotechUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'persistValveState' : IDL.Func(
        [IDL.Vec(IDL.Tuple(ValveName, IDL.Bool))],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([HydrotechUserProfile], [], []),
    'setPersistentValveState' : IDL.Func([IDL.Nat], [], []),
    'submitPersistentShopOrder' : IDL.Func([ShopOrder], [], []),
  });
};

export const init = ({ IDL }) => { return []; };