/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlertEntry {
  'isAcknowledged' : boolean,
  'message' : string,
  'severity' : AlertSeverity,
}
export type AlertSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface HydrotechUserProfile {
  'displayName' : string,
  'customWebId' : string,
  'email' : string,
}
export interface ServiceBooking {
  'technicianName' : string,
  'bookingDate' : Time,
  'notes' : string,
}
export interface ShopOrder {
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type ValveName = string;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acknowledgeAlert' : ActorMethod<[bigint], undefined>,
  'addPersistentServiceBooking' : ActorMethod<[ServiceBooking], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearPersistentState' : ActorMethod<[], undefined>,
  'createPersistentAlert' : ActorMethod<[AlertEntry], bigint>,
  'getAlerts' : ActorMethod<[], Array<[bigint, AlertEntry]>>,
  'getCallerServiceBookings' : ActorMethod<[], Array<ServiceBooking>>,
  'getCallerShopOrders' : ActorMethod<[], Array<ShopOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [HydrotechUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPersistentValveState' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [HydrotechUserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'persistValveState' : ActorMethod<[Array<[ValveName, boolean]>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[HydrotechUserProfile], undefined>,
  'setPersistentValveState' : ActorMethod<[bigint], undefined>,
  'submitPersistentShopOrder' : ActorMethod<[ShopOrder], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];